### ISSUE TITLE
Project name is undefined in status bar

### ISSUE THREAD

**Issue by brice-noowu** [willasm/version-inc#1]
Hi, and thank you for this plugin that does exactly what I was looking for.

Seems that my project name (I assume, the "name" properties of package.json ?) doesnt show in the status bar, instead I have undefined.
I tried to reload / restart vscode, but same : 

![image](https://user-images.githubusercontent.com/49209525/150680298-3e281585-d7f5-464c-a70f-cd4d87204e4e.png)

**Comment by brice-noowu** [comment]
My bad, just saw in the sources that you're using "displayName" instead of juste "name". Closed !

**Comment by willasm** [comment]
Thanks for spotting that. Now defaults to "name" if "displayName" is not defined in v0-0-0-5.
